config/routes.rb
AffiliateApp::Application.routes.draw do

  root :to => 'dashboard#show'

  resources :affiliates

end

app/models/affiliate.rb
class Affiliate < ActiveRecord::Base
  attr_accessible :facebook, :joined_on, :name, :subtitle, :twitter
end

app/controllers/affiliates_controller.rb
class AffiliatesController < ApplicationController

  def index
    @affiliates = Affiliate.all
  end

  def show
    @affiliate = Affiliate.find(params[:id])
  end

  def new
    @affiliate = Affiliate.new
  end

  def create
    affiliate = Affiliate.create(params[:affiliate])
    redirect_to affiliate
  end

  def edit
    @affiliate = Affiliate.find(params[:id])
  end

  def update
    affiliate = Affiliate.find(params[:id])
    affiliate.update_attributes(params[:affiliate])
    redirect_to affiliate
  end

  def destroy
    affiliate = Affiliate.find(params[:id])
    affiliate.destroy
    redirect_to affiliates_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/affiliates/edit.html.slim
h1 Edit #{@affiliate.name}

= form_for @affiliate do |f|
  = f.text_field :name, placeholder: 'Name'
  = f.text_field :twitter, placeholder: 'Twitter Username'
  = f.submit

app/views/affiliates/index.html.slim
h2 Our Affiliates
= link_to "Create a New Group!", new_affiliate_path
- @affiliates.each do |affiliate|
  div= link_to affiliate.name, affiliate

app/views/affiliates/new.html.slim
h1 Create a new affiliate

= form_for @affiliate do |f|
  = f.text_field :name, placeholder: 'Name'
  = f.text_field :twitter, placeholder: 'Twitter Username'
  = f.submit

app/views/affiliates/show.html.slim
= link_to 'Back to affilates index', Affiliate

h1= @affiliate.name

= link_to 'Get em outta here!', affiliate_path(@affiliate), method: :delete

div
  ' twitter:
  = @affiliate.twitter

app/views/dashboard/show.html.slim
h1 Dashboard

= link_to 'View Affiliates', affiliates_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title SSA Affiliate App
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  body
    nav
      h3 SSA Affiliate App
      hr
    = yield